const grades=["7th grade","8th grade","Freshman","Sophomore","Junior","Senior"];
const states=["South Carolina","Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"];
const ls={profile:"nlr_profile",contacts:"nlr_contacts",targets:"nlr_targets"};
const profileFields=["name","grade","graduationYear","state","school","travelTeam","sport","primaryPosition","secondaryPosition","gpa","height","batsThrows","homeToFirst","overhandVelocity","exitVelocity","popTime","pitchingVelocity","videoLinks","socialLinks","recruitingStage","goal","position","targetSchoolsAdded","coachesContacted"];
const contactFields=["school","division","coachName","coachEmail","dateContacted","response","nextFollowUp","notes"];
const targetFields=["schoolName","division","location","coachName","coachEmail","academicFit","athleticFit","costNotes","interestLevel","status"];
const roadmap={};grades.forEach(g=>roadmap[g]={matter:`At ${g}, prioritize academics, skill growth, coachability, and consistency.`,notMatter:"Rankings and hype do not matter as much as daily development.",athlete:["Train fundamentals 4-5x/week","Track metrics and grades","Keep social media positive"],parent:["Support routines","Track budget","Communicate with coaches calmly"],coach:["Give honest evals","Build development plan","Document progress"],monthly:["Review film","Update profile","Plan next events"],mistakes:["Ignoring academics","Emailing too broadly too early","Skipping recovery"],next:"Complete this month's checklist and update metrics."});
const recruitingCards=["NCAA D1","NCAA D2","NCAA D3","NAIA","JUCO","Contact periods","Evaluation periods","Quiet periods","Dead periods","Official visits","Unofficial visits","Eligibility center","Scholarships","Verbal offers"];
const videoData={Pitcher:["Full windup + stretch","Fastball/change/secondary pitch","Length: 3-5 min","Angle: behind catcher + open side","Show command and velo trends","Avoid shaky footage"],Catcher:["Pop times to 2nd","Blocking and framing","Length: 3-4 min","Angle: behind pitcher and 1B side","Show transfer speed","Avoid long intros"],Infielder:["Forehand/backhand","Double-play feeds","Length: 3-4 min","Angle: elevated side","Show footwork + arm strength","Avoid dark lighting"],Outfielder:["Reads and routes","Long throws","Length: 3-4 min","Angle: behind home + side","Show speed and carry","Avoid editing effects"],Hitter:["Front + side swing","Game at-bats","Length: 3-5 min","Angle: open-side tripod","Show contact quality","Avoid too many tee swings"],Slapper:["Bunt/slap variations","First-step speed","Length: 3-4 min","Angle: 1B line","Show timing and pressure","Avoid missing full-field context"],"Utility player":["Mixed defensive reps","Offensive versatility","Length: 4-6 min","Angle: multiple clear angles","Show adaptability","Avoid repeating same rep"]};

function makeForm(containerId, fields){const el=document.getElementById(containerId);el.innerHTML="";fields.forEach(f=>{const w=document.createElement("div");if(["videoLinks","socialLinks","notes"].includes(f))w.className="wide";w.innerHTML=`<label>${f.replace(/([A-Z])/g,' $1')}</label><input name="${f}"/>`;el.appendChild(w);});}
makeForm("profileForm",profileFields);makeForm("contactForm",contactFields);makeForm("targetForm",targetFields);

const p=JSON.parse(localStorage.getItem(ls.profile)||"{}");fillForm("profileForm",p);
function fillForm(id,data){document.querySelectorAll(`#${id} [name]`).forEach(i=>{if(i.name==="grade")buildGradeInput(i);if(i.name==="state")buildStateInput(i);if(i.name==="goal")i.outerHTML='<select name="goal"><option>D1</option><option>D2</option><option>D3</option><option>NAIA</option><option>JUCO</option><option>unsure</option></select>';});document.querySelectorAll(`#${id} [name]`).forEach(i=>i.value=data[i.name]||"");}
function buildGradeInput(i){i.outerHTML='<select name="grade">'+grades.map(g=>`<option>${g}</option>`).join("")+"</select>"}
function buildStateInput(i){i.outerHTML='<select name="state">'+states.map(s=>`<option>${s}</option>`).join("")+"</select>"}

function formData(id){const d={};document.querySelectorAll(`#${id} [name]`).forEach(i=>d[i.name]=i.value.trim());return d}
function saveProfile(){const d=formData("profileForm");localStorage.setItem(ls.profile,JSON.stringify(d));renderHome();renderTemplate();alert("Profile saved locally.")}
document.getElementById("saveProfileBtn").onclick=saveProfile;

function renderHome(){const d=JSON.parse(localStorage.getItem(ls.profile)||"{}");document.getElementById("snapshot").innerHTML=`<p><b>${d.name||"Athlete"}</b> | ${d.grade||"Grade"} | ${d.state||"State"}</p><p>${d.sport||"Softball"} - ${d.primaryPosition||"Position"} | Goal: ${d.goal||"unsure"}</p>`;
const checks=[d.name,d.grade,d.state,d.school,d.primaryPosition,d.gpa,d.videoLinks,d.goal,d.socialLinks,d.targetSchoolsAdded,d.coachesContacted];const pct=Math.round(checks.filter(Boolean).length/checks.length*100);document.getElementById("progressBar").style.width=pct+"%";document.getElementById("progressText").textContent=pct+"%";
const action=getWeeklyAction(d,pct);document.getElementById("weeklyAction").textContent=action;
const tasks=["Update skill metrics","Review grade roadmap","Add one target school","Log one coach contact","Verify state eligibility rules"].slice(0,3);document.getElementById("nextTasks").innerHTML=tasks.map(t=>`<li>${t}</li>`).join("");
const alerts=[];if(!d.videoLinks)alerts.push("No video link saved.");if(!d.gpa)alerts.push("GPA missing.");if(!d.state)alerts.push("State not selected.");document.getElementById("alerts").innerHTML=(alerts.length?alerts:["All core items present."]).map(a=>`<li>${a}</li>`).join("");}
function getWeeklyAction(d,pct){if(d.grade==="8th grade")return "Focus on fundamentals, grades, speed development, and building a video library. Do not worry about mass emailing college coaches yet.";if(d.grade==="Sophomore"&&!d.videoLinks)return"Your next priority is building a clean skills video before contacting more programs.";if(d.grade==="Junior"&&d.targetSchoolsAdded&& !d.coachesContacted)return"Start sending personalized emails to realistic-fit schools and include your schedule, profile, video, GPA, and position.";if((+d.gpa||0)<3)return"Prioritize GPA recovery and tutoring this week.";if(pct<60)return"Complete missing profile fields and add at least 5 target schools.";return"Keep momentum: personalize outreach and update your contact log after each event."}

const gradeSel=document.getElementById("roadmapGrade");gradeSel.innerHTML=grades.map(g=>`<option>${g}</option>`).join("");gradeSel.onchange=()=>renderRoadmap(gradeSel.value);
function renderRoadmap(g){const r=roadmap[g];document.getElementById("roadmapContent").innerHTML=`<h3>${g}</h3><p><b>What matters right now:</b> ${r.matter}</p><p><b>What does not matter yet:</b> ${r.notMatter}</p><p><b>Athlete tasks:</b> ${r.athlete.join(", ")}</p><p><b>Parent tasks:</b> ${r.parent.join(", ")}</p><p><b>Coach tasks:</b> ${r.coach.join(", ")}</p><p><b>Monthly checklist:</b> ${r.monthly.join(", ")}</p><p><b>Common mistakes:</b> ${r.mistakes.join(", ")}</p><p><b>Recommended next step:</b> ${r.next}</p>`}
renderRoadmap(grades[0]);

const stateSel=document.getElementById("stateRulesSelect");stateSel.innerHTML=states.map(s=>`<option ${s==='South Carolina'?'selected':''}>${s}</option>`).join("");
stateSel.onchange=()=>renderState(stateSel.value);
function renderState(s){document.getElementById("stateRuleCard").innerHTML=`<h4>${s}</h4><p>State athletic association: Placeholder for ${s} association.</p><p>Middle school note: Participation and transfer policies vary.</p><p>High school reminder: Verify semester, age, and enrollment eligibility.</p><p>Transfer/age/grade warning: Rules differ by district and sanctioning body.</p><p>Official rules link: [Add ${s} official eligibility URL]</p><p><b>Disclaimer:</b> Verify with official state association, school district, and athletic director.</p>`}
renderState("South Carolina");
document.getElementById("recruitingRules").innerHTML='<h3>Recruiting Rules Guide</h3>'+recruitingCards.map(c=>`<p><b>${c}:</b> Plain-English overview placeholder with current-rule verification reminder.</p>`).join("");

function renderTemplate(){const d=JSON.parse(localStorage.getItem(ls.profile)||"{}");const school=(JSON.parse(localStorage.getItem(ls.targets)||"[]")[0]||{}).schoolName||"[College Name]";const map={intro:`Subject: ${d.name||"Athlete"} - ${d.primaryPosition||"Position"} - ${d.graduationYear||"Grad Year"}\n\nCoach, my name is ${d.name||"[Name]"}. I'm interested in ${school}. GPA: ${d.gpa||"[GPA]"}. Video: ${d.videoLinks||"[Link]"}.`,followup:`Coach, following up on my previous email. I remain very interested in your program and can share updated schedule/video.`,schedule:`Coach, here is my upcoming tournament schedule: [Dates/Fields]. I would value any opportunity to be evaluated.`,camp:`Coach, I'm planning to attend your camp and wanted to introduce myself ahead of time.`,thanks:`Coach, thank you for your time and feedback. I appreciate your guidance.`};document.getElementById("templateOutput").value=map[document.getElementById("templateType").value];}
document.getElementById("templateType").onchange=renderTemplate;renderTemplate();

function addListItem(formId,key,listId,labeler){const arr=JSON.parse(localStorage.getItem(key)||"[]");arr.push(formData(formId));localStorage.setItem(key,JSON.stringify(arr));renderList(key,listId,labeler)}
function renderList(key,listId,labeler){const arr=JSON.parse(localStorage.getItem(key)||"[]");document.getElementById(listId).innerHTML=arr.map((i,n)=>`<article class='card'><b>${n+1}. ${labeler(i)}</b><p>${Object.entries(i).map(([k,v])=>`${k}: ${v||'-'}`).join("<br>")}</p></article>`).join("")||"<p>No entries yet.</p>"}
document.getElementById("addContactBtn").onclick=()=>addListItem("contactForm",ls.contacts,"contactList",i=>`${i.school||"School"} - ${i.coachName||"Coach"}`);
document.getElementById("addTargetBtn").onclick=()=>addListItem("targetForm",ls.targets,"targetList",i=>`${i.schoolName||"School"} (${i.status||"research"})`);
renderList(ls.contacts,"contactList",i=>`${i.school||"School"} - ${i.coachName||"Coach"}`);renderList(ls.targets,"targetList",i=>`${i.schoolName||"School"} (${i.status||"research"})`);

const vr=document.getElementById("videoRole");vr.innerHTML=Object.keys(videoData).map(v=>`<option>${v}</option>`).join("");vr.onchange=()=>{const d=videoData[vr.value];document.getElementById("videoChecklist").innerHTML=`<h3>${vr.value} Checklist</h3><ul>${d.map(x=>`<li>${x}</li>`).join("")}</ul>`};vr.onchange();

const parentSections=["Recruiting cost tracker","Camp decision guide","Travel ball decision guide","Scholarship reality check","Red flags to avoid","Questions to ask college coaches","Academic checklist","Eligibility checklist"];document.getElementById("parentDashboard").innerHTML=parentSections.map(s=>`<article class='card'><h3>${s}</h3><p>Guidance placeholder and action checklist.</p></article>`).join("");
const coachSections=["Team recruiting overview","Player readiness checklist","Suggested player guidance","Coach notes","Parent communication talking points","Player development priorities"];document.getElementById("coachDashboard").innerHTML=coachSections.map(s=>`<article class='card'><h3>${s}</h3><p>Program-level planning notes and reminders.</p></article>`).join("");

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
renderHome();
